### PR TITLE
Make some async api work on Scala.js and Native

### PR DESCRIPTION
**Pull request by lolgab**
This PR breaks binary compatibility in Scala.js and Scala Native but
doesn't touch binary compatibility for Scala JVM.
Since the methods removed weren't linking on JS/Native this can be
released as a patch release, until we find an API that works seamlessly in
all the platforms.
This deprecates `Context.Impl.scheduler` which cannot be implemented on
Native and JS and suggests to use `scheduleMsg` instead.

`scheduleMsg` is removed from Scala.js and Scala Native. We should probably
add an alternative using `scala.concurrent.duration` so it can be implemented in
all platforms, but since it wasn't working it is fine to remove for now since nobody
could use it either way.

`./mill -i  __.jvm.__.mimaReportBinaryIssues` passes all binary compatibility checks

### CODE REVIEW

**Comment by lihaoyi** [comment]
@lolgab is it possible to duplicate less of the code? If the only thing that differs is `scheduler`/`scheduleMsg`, I'd only expect to see that logic changed between JVM/JS/Native and the rest of the boilerplate in Context.scala unchanged

**Comment by lolgab** [comment]
It is possible if we change the API in a breaking way.
We need to either:
- Change `scheduleMsg` signature from:
```diff
-def scheduleMsg[T](a: Actor[T],msg: T, delay: java.time.Duration)(implicit fileName: sourcecode.FileName, line: sourcecode.Line)
+def scheduleMsg[T](a: Actor[T],msg: T, delay: scala.concurrent.duration.FiniteDuration)(implicit fileName: sourcecode.FileName, line: sourcecode.Line)
```
- or make the library depend on https://github.com/cquiroz/scala-java-time on JS (Native not yet supported) which is a big library and an overkill for this use case IMO.

Also I removed `Context.Simple.threadPool`, `Context.makeThreadPool`, `Context.ThreadPool`, `Context.TestThreadPool` from JS and Native and we need to find them another home if we want to duplicate less code.

My idea was to live with this for a bit until we find an API that works on all platforms that we are happy with and release a breaking version.

Let me know what approach you think is the best and I can try to implement it. :)

**Comment by lihaoyi** [comment]
Could we add an override that takes FiniteDuration? that way people who
want to use it cross-platform can do so, while those who have code on the
JVM using java.time can continue using the existing API without change

**Comment by lolgab** [comment]
Sadly you can't leave methods using `java.time` or `java.util.concurrent` in public traits without making the Scala.js linker complain ( Scala Native links just fine but it might be a bug ).
I tried another approach with mixins which is source compatible but not binary compatible ( it will require us to tag `0.2.0` ).
Please give a look and let me know what you think.

**Comment by lihaoyi** [comment]
Looks good to me I think

**Comment by lolgab** [comment]
@lihaoyi Ready for the final review. 
Tests are green ✅.

**Comment by lihaoyi** [comment]
Tagging 0.2.0 sounds good. Castor is still a relatively young library, so we should expect it to evolve over time where necessary.

Skimmed over the changes, looks good to me

**Comment by lolgab** [comment]
`0.2.0` was released. I also noticed there was already an issue open ( #7 ) which this PR fixed, so I closed it :)

**Pull request merged**
